# Generated by jeweler
# DO NOT EDIT THIS FILE DIRECTLY
# Instead, edit Jeweler::Tasks in Rakefile, and run 'rake gemspec'
# -*- encoding: utf-8 -*-

Gem::Specification.new do |s|
  s.name = "cpgem"
  s.version = "0.0.1"

  s.required_rubygems_version = Gem::Requirement.new(">= 0") if s.respond_to? :required_rubygems_version=
  s.authors = ["Jesus Lopes"]
  s.date = "2011-09-23"
  s.description = "Copy Gemfile line to clipboard"
  s.email = "jlopes@zigotto.com.br"
  s.executables = ["cpgem"]
  s.extra_rdoc_files = [
    "LICENSE.txt",
    "README.rdoc"
  ]
  s.files = [
    ".document",
    ".rspec",
    "Gemfile",
    "Gemfile.lock",
    "LICENSE.txt",
    "README.rdoc",
    "Rakefile",
    "VERSION",
    "bin/cpgem",
    "features/cpgem.feature",
    "features/step_definitions/cpgem_steps.rb",
    "features/support/env.rb",
    "lib/cpgem.rb",
    "spec/cpgem_spec.rb",
    "spec/spec_helper.rb"
  ]
  s.homepage = "http://github.com/zigotto/cpgem"
  s.licenses = ["MIT"]
  s.require_paths = ["lib"]
  s.rubygems_version = "1.8.10"
  s.summary = "Copy Gemfile line to clipboard"

  if s.respond_to? :specification_version then
    s.specification_version = 3

    if Gem::Version.new(Gem::VERSION) >= Gem::Version.new('1.2.0') then
      s.add_runtime_dependency(%q<main>, ["~> 4.7.6"])
      s.add_runtime_dependency(%q<gems>, ["~> 0.5.0"])
      s.add_runtime_dependency(%q<clipboard>, ["~> 0.9.9"])
      s.add_development_dependency(%q<aruba>, ["~> 0.4.6"])
      s.add_development_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_development_dependency(%q<cucumber>, ["~> 1.1.0"])
      s.add_development_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_development_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_development_dependency(%q<rcov>, ["~> 0.9.10"])
    else
      s.add_dependency(%q<main>, ["~> 4.7.6"])
      s.add_dependency(%q<gems>, ["~> 0.5.0"])
      s.add_dependency(%q<clipboard>, ["~> 0.9.9"])
      s.add_dependency(%q<aruba>, ["~> 0.4.6"])
      s.add_dependency(%q<rspec>, ["~> 2.6.0"])
      s.add_dependency(%q<cucumber>, ["~> 1.1.0"])
      s.add_dependency(%q<bundler>, ["~> 1.0.0"])
      s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
      s.add_dependency(%q<rcov>, ["~> 0.9.10"])
    end
  else
    s.add_dependency(%q<main>, ["~> 4.7.6"])
    s.add_dependency(%q<gems>, ["~> 0.5.0"])
    s.add_dependency(%q<clipboard>, ["~> 0.9.9"])
    s.add_dependency(%q<aruba>, ["~> 0.4.6"])
    s.add_dependency(%q<rspec>, ["~> 2.6.0"])
    s.add_dependency(%q<cucumber>, ["~> 1.1.0"])
    s.add_dependency(%q<bundler>, ["~> 1.0.0"])
    s.add_dependency(%q<jeweler>, ["~> 1.6.4"])
    s.add_dependency(%q<rcov>, ["~> 0.9.10"])
  end
end

